# Generated by Django 3.1 on 2020-10-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lotteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_lotte', models.TextField()),
                ('lotteImage', models.ImageField(blank=True, upload_to='images/')),
                ('lotteUrl', models.TextField()),
                ('lotteName', models.TextField()),
                ('lottePrice', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lottedata'),
        ),
        migrations.DeleteModel(
            name='musinsaData',
        ),
    ]
