# Generated by Django 3.1 on 2020-10-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsaved',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/temp/'),
        ),
    ]
