# Generated by Django 3.1 on 2020-08-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wear_mywear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_want_wear', models.ImageField(blank=True, upload_to='images/shoplist')),
            ],
        ),
    ]
