# Generated by Django 3.1 on 2020-10-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201021_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(choices=[('seoul', '서울'), ('gyeonggi', '경기'), ('chungnam', '충남'), ('chungbuk', '충북'), ('gyeongbuk', '경북'), ('gyeongnam', '경남'), ('jeonbuk', '전북'), ('jeonnam', '전남')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('여성', '여성'), ('남성', '남성')], max_length=50),
        ),
    ]
