# Generated by Django 3.1 on 2020-10-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lotteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_lotte', models.TextField()),
                ('lotteImage', models.ImageField(blank=True, upload_to='images/')),
                ('lotteUrl', models.TextField()),
                ('lotteName', models.TextField()),
                ('lottePrice', models.IntegerField()),
                ('category', models.TextField()),
            ],
        ),
    ]
